name: Deploy GoatManagementBackend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Backend Dependencies
        run: |
          cd Backend
          npm ci

      - name: Build Backend
        run: |
          cd Backend
          npm run build

      - name: Set up SSH Agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 162.0.224.102 >> ~/.ssh/known_hosts

      - name: Clean old backend files on server
        run: |
          ssh -i ~/.ssh/id_rsa root@162.0.224.102 << 'EOF'
            rm -rf /var/www/goatmanagementbackend
          EOF

      - name: Upload Backend to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 162.0.224.102
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "Backend/**"
          target: "/var/www/goatmanagementbackend"
